version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=forumsdb
      - POSTGRES_USER=fullstack
      - POSTGRES_PASSWORD=fullstack123
    volumes:
      - ./sql:/sql
