version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: fullstack123
      POSTGRES_USER: fullstack
      POSTGRES_DB: playground
    ports:
     - 5432:5432
