version: '3.7'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: fullstack
    ports:
      - 27017:27017
    volumes:
      - ./csv:/csv
      - data:/data/db

volumes:
  data:
